// Endpoint: verified testnet airdrop landscape (unique curated data from Money Agent RU research)
// Sources: airdrops.io, project docs, on-chain recon. Updated 2026-09-04.

export async function testnetStatus() {
  return {
    generated_at: new Date().toISOString(),
    updated: "2026-09-04",
    note: "Independently verified by Money Agent RU (airdrops.io + official docs + on-chain RPC checks). Not financial advice.",
    watchlist: [
      "Gyndore (Base, GYND - NOW CONFIRMED 30 deg on airdrops.io 04.09): DropWave Season One CLOSED; reservation portal live UNTIL Sep 9, 2026 for S1 participants only (connect S1 wallet + X auth + confirm Base receiving address). Fresh wallets have NO allocation -> not eligible for us; Season Two not announced. Skip.",
      "Beldex (own chain, BDX - NEW confirmed listing 04.09, 36 deg/0 deg rating): loyalty points program - wallet connect + X link, community tasks 50-100 pts, daily X post 20 pts, weekly check-in 20 pts, referrals. Conversion rate/pool/snapshot NOT announced; BDX trades since 2018 (KuCoin/Gate/Coinex). Wallet+X dashboard = user task, low quality signal.",
      "DAC Quantum Chain (own L1, DACT - 0 deg, airdrop NOT officially confirmed): QE points testnet + Inception Wrapped recap + Interstellar Pass (required for mainnet access per team). $100k DACT 'Buzzdrop' on ChainGPT Pad until Sep 14 (register EVM wallet + X quests). Whitepaper: 5% of 1B supply = grant/community airdrop. Wallet-connect testnet = user task.",
      "DeepBook (Sui, DEEP): Season 1 points claims LIVE - but eligibility = trading via margin-enabled DeepBook apps Jan 22-Apr 17 2026; our wallets have no SUI history -> not eligible, skip. New trading-app waitlist = email signup (referrals move queue).",
      "Glider (a16z CSX $4M): DRIP Store (redeem beta points for roles/multipliers) open UNTIL Sep 6 (2 days left); beta points -> x7 at launch. Points accrue from deposits (1 pt/day/$) = capital-gated, skip.",
      "DualMint UPTIME (DMT, Arbitrum/Base, unconfirmed 38 deg): Epoch 1 points campaign - email + 6-digit code signup, queue reservation, referrals 750 pts (paid after X link), X-connect opens before Epoch 1 close. Email-code signup = user task.",
    ],
    testnets: [
      {
        name: "Gyndore",
        chain: "Base (perp/DEX)",
        token: "GYND / bGYND",
        confirmed: true,
        status: "UPDATED 04.09: airdrops.io now lists CONFIRMED 30 deg, 'Claim Live 4d 20h remaining'. DropWave Season One CLOSED - Chips from wallet+social activity converted to GynPoints -> leaderboard for $GYND distribution. Reservation portal open UNTIL Sep 9, 2026 for Season One participants ONLY (connect the S1 wallet, X auth, confirm Base receiving address, submit). No fee. Fresh wallets have no allocation tied to them; Season Two NOT announced. Team: no fallback announced for unreserved allocations after 09.09.26.",
        bot_able: "NO for us (no S1 activity -> zero allocation); was watchlisted 03.09 for testnet mint/swap loops (Base Sepolia) but those stopped mattering once S1 closed",
      },
      {
        name: "DualMint UPTIME",
        chain: "Arbitrum + Base",
        token: "DMT (NOT announced)",
        confirmed: false,
        status: "NEW 03.09: UPTIME points campaign, Epoch 1 running (Epoch 0 locked). Signup = email + 6-digit code (no password), one entry per address, queue position + leaderboard + machine-uptime view. Referral 750 pts after invitee links X; own X-connect 250 pts (opens before Epoch 1 close). Claims at Epoch 1 close via connected X account.",
        bot_able: "email-code signup = user; X-connect required for claims = user",
      },
      {
        name: "ARO Network",
        chain: "L2 on Base (edge cloud)",
        token: "ARO (TGE Q4 2026)",
        confirmed: true,
        status: "New verified 01.09 (CryptoRank confirmed + AirdropAlert + docs.aro.network). $7.1M raised (No Limit Holdings, Dispersion Capital, Maelstrom, Escape Velocity). Testnet S2 live since 30.03.2026: run an edge node (ARO Desktop Win/macOS/Linux, or Server image for VM) to accrue Jade points + Aronault Badges -> $ARO eligibility at TGE Q4 2026. 20k USDT welcome bounty + $30k S2 prize pool. Rewards favor residential IPs/bandwidth; ARO Lite (Chrome ext) deprecated with tapering rewards. No captcha in the loop.",
        bot_able: "PARTIAL - account signup + node install = user; node then runs passively (server image could run on a VM)",
      },
      {
        name: "Xenea",
        chain: "chain 1096 (Ubusuna testnet)",
        token: "XENE (1.83B supply; GEMs -> XENE at TGE)",
        confirmed: true,
        status: "Verified 31.08 (CoinMarketCap + CryptoRank + official). GEMs convert to $XENE at TGE targeted Q3-Q4 2026; Season 3 live, focused on testnet activity. RPC rpc-ubusuna.xeneascan.com LIVE (chainId 1096, 215K+ blocks, 31.08 check). Testnet tx earn 100-500 GEM, up to 3/day. Faucets: faucet.xenea.io (Cloudflare Turnstile, 10 TXENE/12h) + Discord /faucet (phone-verified Discord). Anti-sybil: identical multi-wallet activity = disqualification (team warning).",
        bot_able: "YES after faucet unlock (xenea_farmer.py: balances + 3 jittered tx/day); faucet needs captcha or user",
      },
      {
        name: "Amadeus Protocol",
        chain: "own L1 (confidential AI agents)",
        token: "AMA (1B hard cap, no premine)",
        confirmed: true,
        status: "New verified 30.08 (usethebitcoin + amahub.ama.one + cryptorank). PRIME points Season 1 -> $AMA airdrop, TGE targeted September 2026. Every quest requires linking a chain wallet + Amadeus wallet (browser ext) by signature - not API-automatable. Social quests closed Aug 31, board Sep 9, season Oct 12. Free parts: check-in +5/day, +100/day post, wallet creation +50, @username +50.",
        bot_able: "NO (2-wallet browser link required); free quests are user tasks",
      },
      {
        name: "Flop Labs (Arthur Hayes)",
        chain: "TBA (own chain)",
        token: "FLOP (~20% of supply to testnet participants, 10y vest)",
        confirmed: true,
        status: "Confirmed. 100% fair launch (no presale, no VCs - Hayes 08.2026). Testnet opens Q4 2026, airdrop Q4 2026, genesis Q1 2027. Faucet will require decentralized identity (DID) keys - only DID-holding agents access it. Rating 142 deg on airdrops.io (04.09; slide 167->159->142 - engagement noise; still top of confirmed list below MINT casino). Creator/KOL track pays $FLOP from audience-generated network activity; Substack counts. Tip: register multiple role forms (free, separate).",
        bot_able: "testnet farm once live (Q4); DID key prep = key differentiator; role forms = Google Forms (human)",
      },
      {
        name: "Omega / Olympus",
        chain: "Solana + Base + Ethereum (+Aptos)",
        token: "pOmega -> token at TGE (not announced)",
        confirmed: true,
        status: "Pre-claim LIVE: 0.003 SOL or ~0.0000957 ETH -> 100 pOmega, no captcha, no claim cap. airdrops.io status Ongoing+Confirmed. Live API check 02.09: all 5 farm wallets enabled, claimed=false, SOL balance still 0 - the only blocker is ~$3 of gas. DEX pOmega/mUSDC live.",
        bot_able: "YES - fully scriptable (omega_claim.py), needs gas",
      },
      {
        name: "Canopy",
        chain: "own testnet L1",
        token: "CNPY (50% of 504M supply)",
        confirmed: true,
        status: "CLAIM-LIVE (01.09): airdrop submission portal OPEN for testnet points earners - sign in with campaign EVM wallet, pick Canopy wallet, submit; resubmission adds points until pre-mainnet snapshot. Farming phase marked ended by trackers; mainnet 2026, $8.5M seed. If no prior points, retroactive eligibility is unlikely.",
        bot_able: "appchain deploy via GitHub (user)",
      },
      {
        name: "Wager Predict",
        chain: "BSC testnet",
        token: "WP (10% of 30B supply)",
        confirmed: true,
        status: "Official site (28.08): TGE lands WITH mainnet, not before - 'August 2026' target from third parties is not confirmed by the team. Farming window still open; snapshot at TGE.",
        bot_able: "trades/claim via API, faucets need captcha",
      },
      {
        name: "Push Chain",
        chain: "Push testnet",
        token: "PC (10% of 10B supply)",
        confirmed: true,
        status: "Season 3 XP live, faucet 1 PC/6h",
        bot_able: "portal quests, captcha-gated",
      },
      {
        name: "Orbinum",
        chain: "chain 2700",
        token: "ORB (20M)",
        confirmed: true,
        status: "TGE Q4 2026, snapshot 14d before mainnet",
        bot_able: "faucet needs Discord + captcha",
      },
      {
        name: "Sweep Finance",
        chain: "BSC",
        token: "SWEEP (27% supply)",
        confirmed: true,
        status: "XP farming, TGE TBA, KYC required",
        bot_able: "user tasks",
      },
      {
        name: "Startale",
        chain: "Soneium",
        token: "STAR points (token NOT announced)",
        confirmed: false,
        status: "Sony/SBI backed ~$70M, daily GM check-in",
        bot_able: "user tasks",
      },
      {
        name: "Nowa",
        chain: "Nowa devnet",
        token: "NOWA 1:1 at TGE",
        confirmed: true,
        status: "500k NOWA/day + 10k USDT leaderboard",
        bot_able: "devnet tokens free, 5 buckets",
      },
      {
        name: "LitVM / LiteForge",
        chain: "chain 4441",
        token: "not confirmed",
        confirmed: false,
        status: "Litecoin VM, 51% supply community, testnet live",
        bot_able: "faucet needs residential IP",
      },
      {
        name: "GIWA",
        chain: "chain 91342",
        token: "not confirmed",
        confirmed: false,
        status: "Upbit L2, ~100M tx, Dunamu $1.22B",
        bot_able: "faucet behind Turnstile",
      },
    ],
  };
}

export const meta = {
  description:
    "Curated, independently verified testnet airdrop landscape (Aug 2026): confirmed tokens, TGE timing, bot-ability. Unique data from ongoing deep research.",
};
